<?php

declare(strict_types=1);

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0.
 * /       /
 */

namespace Twilio\Rest\Messaging\V1\Service;

use Twilio\Exceptions\TwilioException;
use Twilio\ListResource;
use Twilio\Version;

/**
 * PLEASE NOTE that this class contains beta products that are subject to change. Use them with caution.
 */
class UsAppToPersonUsecaseList extends ListResource
{
    /**
     * Construct the UsAppToPersonUsecaseList.
     *
     * @param Version $version             Version that contains the resource
     * @param string  $messagingServiceSid The unique string that identifies the
     *                                     resource
     */
    public function __construct(Version $version, string $messagingServiceSid)
    {
        parent::__construct($version);

        // Path Solution
        $this->solution = ['messagingServiceSid' => $messagingServiceSid];

        $this->uri = '/Services/'.\rawurlencode($messagingServiceSid).'/Compliance/Usa2p/Usecases';
    }

    /**
     * Provide a friendly representation.
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string
    {
        return '[Twilio.Messaging.V1.UsAppToPersonUsecaseList]';
    }

    /**
     * Fetch the UsAppToPersonUsecaseInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return UsAppToPersonUsecaseInstance Fetched UsAppToPersonUsecaseInstance
     */
    public function fetch(): UsAppToPersonUsecaseInstance
    {
        $payload = $this->version->fetch('GET', $this->uri);

        return new UsAppToPersonUsecaseInstance(
            $this->version,
            $payload,
            $this->solution['messagingServiceSid']
        );
    }
}
