<?php

declare(strict_types=1);

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0.
 * /       /
 */

namespace Twilio\Rest\Accounts\V1\Credential;

use Twilio\Exceptions\TwilioException;
use Twilio\InstanceContext;
use Twilio\Options;
use Twilio\Values;
use Twilio\Version;

class PublicKeyContext extends InstanceContext
{
    /**
     * Initialize the PublicKeyContext.
     *
     * @param Version $version Version that contains the resource
     * @param string  $sid     The unique string that identifies the resource
     */
    public function __construct(Version $version, $sid)
    {
        parent::__construct($version);

        // Path Solution
        $this->solution = ['sid' => $sid];

        $this->uri = '/Credentials/PublicKeys/'.\rawurlencode($sid).'';
    }

    /**
     * Provide a friendly representation.
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string
    {
        $context = [];
        foreach ($this->solution as $key => $value) {
            $context[] = "{$key}={$value}";
        }

        return '[Twilio.Accounts.V1.PublicKeyContext '.\implode(' ', $context).']';
    }

    /**
     * Fetch the PublicKeyInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return PublicKeyInstance Fetched PublicKeyInstance
     */
    public function fetch(): PublicKeyInstance
    {
        $payload = $this->version->fetch('GET', $this->uri);

        return new PublicKeyInstance($this->version, $payload, $this->solution['sid']);
    }

    /**
     * Update the PublicKeyInstance.
     *
     * @param array|Options $options Optional Arguments
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return PublicKeyInstance Updated PublicKeyInstance
     */
    public function update(array $options = []): PublicKeyInstance
    {
        $options = new Values($options);

        $data = Values::of(['FriendlyName' => $options['friendlyName']]);

        $payload = $this->version->update('POST', $this->uri, [], $data);

        return new PublicKeyInstance($this->version, $payload, $this->solution['sid']);
    }

    /**
     * Delete the PublicKeyInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return bool True if delete succeeds, false otherwise
     */
    public function delete(): bool
    {
        return $this->version->delete('DELETE', $this->uri);
    }
}
