<?php

declare(strict_types=1);

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0.
 * /       /
 */

namespace Twilio\Rest\Pricing\V2\Voice;

use Twilio\Exceptions\TwilioException;
use Twilio\InstanceContext;
use Twilio\Version;

class CountryContext extends InstanceContext
{
    /**
     * Initialize the CountryContext.
     *
     * @param Version $version    Version that contains the resource
     * @param string  $isoCountry The ISO country code of the pricing information to
     *                            fetch
     */
    public function __construct(Version $version, $isoCountry)
    {
        parent::__construct($version);

        // Path Solution
        $this->solution = ['isoCountry' => $isoCountry];

        $this->uri = '/Voice/Countries/'.\rawurlencode($isoCountry).'';
    }

    /**
     * Provide a friendly representation.
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string
    {
        $context = [];
        foreach ($this->solution as $key => $value) {
            $context[] = "{$key}={$value}";
        }

        return '[Twilio.Pricing.V2.CountryContext '.\implode(' ', $context).']';
    }

    /**
     * Fetch the CountryInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return CountryInstance Fetched CountryInstance
     */
    public function fetch(): CountryInstance
    {
        $payload = $this->version->fetch('GET', $this->uri);

        return new CountryInstance($this->version, $payload, $this->solution['isoCountry']);
    }
}
