<?php

declare(strict_types=1);

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0.
 * /       /
 */

namespace Twilio\Rest\Trusthub\V1\CustomerProfiles;

use Twilio\Exceptions\TwilioException;
use Twilio\InstanceContext;
use Twilio\Version;

class CustomerProfilesEntityAssignmentsContext extends InstanceContext
{
    /**
     * Initialize the CustomerProfilesEntityAssignmentsContext.
     *
     * @param Version $version            Version that contains the resource
     * @param string  $customerProfileSid the unique string that identifies the
     *                                    resource
     * @param string  $sid                The unique string that identifies the resource
     */
    public function __construct(Version $version, $customerProfileSid, $sid)
    {
        parent::__construct($version);

        // Path Solution
        $this->solution = ['customerProfileSid' => $customerProfileSid, 'sid' => $sid];

        $this->uri = '/CustomerProfiles/'.\rawurlencode($customerProfileSid).'/EntityAssignments/'.\rawurlencode($sid).'';
    }

    /**
     * Provide a friendly representation.
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string
    {
        $context = [];
        foreach ($this->solution as $key => $value) {
            $context[] = "{$key}={$value}";
        }

        return '[Twilio.Trusthub.V1.CustomerProfilesEntityAssignmentsContext '.\implode(' ', $context).']';
    }

    /**
     * Fetch the CustomerProfilesEntityAssignmentsInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return CustomerProfilesEntityAssignmentsInstance Fetched
     *                                                   CustomerProfilesEntityAssignmentsInstance
     */
    public function fetch(): CustomerProfilesEntityAssignmentsInstance
    {
        $payload = $this->version->fetch('GET', $this->uri);

        return new CustomerProfilesEntityAssignmentsInstance(
            $this->version,
            $payload,
            $this->solution['customerProfileSid'],
            $this->solution['sid']
        );
    }

    /**
     * Delete the CustomerProfilesEntityAssignmentsInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return bool True if delete succeeds, false otherwise
     */
    public function delete(): bool
    {
        return $this->version->delete('DELETE', $this->uri);
    }
}
