<?php

declare(strict_types=1);

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0.
 * /       /
 */

namespace Twilio\Rest\Preview\BulkExports;

use Twilio\Exceptions\TwilioException;
use Twilio\InstanceResource;
use Twilio\Options;
use Twilio\Values;
use Twilio\Version;

/**
 * PLEASE NOTE that this class contains preview products that are subject to change. Use them with caution. If you currently do not have developer preview access, please contact help@twilio.com.
 *
 * @property bool   $enabled
 * @property string $webhookUrl
 * @property string $webhookMethod
 * @property string $resourceType
 * @property string $url
 */
class ExportConfigurationInstance extends InstanceResource
{
    /**
     * Initialize the ExportConfigurationInstance.
     *
     * @param Version $version      Version that contains the resource
     * @param mixed[] $payload      The response payload
     * @param string  $resourceType The type of communication – Messages, Calls,
     *                              Conferences, and Participants
     */
    public function __construct(Version $version, array $payload, string $resourceType = null)
    {
        parent::__construct($version);

        // Marshaled Properties
        $this->properties = [
            'enabled' => Values::array_get($payload, 'enabled'),
            'webhookUrl' => Values::array_get($payload, 'webhook_url'),
            'webhookMethod' => Values::array_get($payload, 'webhook_method'),
            'resourceType' => Values::array_get($payload, 'resource_type'),
            'url' => Values::array_get($payload, 'url'),
        ];

        $this->solution = ['resourceType' => $resourceType ?: $this->properties['resourceType']];
    }

    /**
     * Magic getter to access properties.
     *
     * @param string $name Property to access
     *
     * @throws TwilioException For unknown properties
     *
     * @return mixed The requested property
     */
    public function __get(string $name)
    {
        if (\array_key_exists($name, $this->properties)) {
            return $this->properties[$name];
        }

        if (\property_exists($this, '_'.$name)) {
            $method = 'get'.\ucfirst($name);

            return $this->{$method}();
        }

        throw new TwilioException('Unknown property: '.$name);
    }

    /**
     * Provide a friendly representation.
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string
    {
        $context = [];
        foreach ($this->solution as $key => $value) {
            $context[] = "{$key}={$value}";
        }

        return '[Twilio.Preview.BulkExports.ExportConfigurationInstance '.\implode(' ', $context).']';
    }

    /**
     * Fetch the ExportConfigurationInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return ExportConfigurationInstance Fetched ExportConfigurationInstance
     */
    public function fetch(): ExportConfigurationInstance
    {
        return $this->proxy()->fetch();
    }

    /**
     * Update the ExportConfigurationInstance.
     *
     * @param array|Options $options Optional Arguments
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return ExportConfigurationInstance Updated ExportConfigurationInstance
     */
    public function update(array $options = []): ExportConfigurationInstance
    {
        return $this->proxy()->update($options);
    }

    /**
     * Generate an instance context for the instance, the context is capable of
     * performing various actions.  All instance actions are proxied to the context.
     *
     * @return ExportConfigurationContext Context for this
     *                                    ExportConfigurationInstance
     */
    protected function proxy(): ExportConfigurationContext
    {
        if (!$this->context) {
            $this->context = new ExportConfigurationContext($this->version, $this->solution['resourceType']);
        }

        return $this->context;
    }
}
