<?php

declare(strict_types=1);

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0.
 * /       /
 */

namespace Twilio\Rest\Events\V1\Sink;

use Twilio\Exceptions\TwilioException;
use Twilio\ListResource;
use Twilio\Version;

/**
 * PLEASE NOTE that this class contains beta products that are subject to change. Use them with caution.
 */
class SinkTestList extends ListResource
{
    /**
     * Construct the SinkTestList.
     *
     * @param Version $version Version that contains the resource
     * @param string  $sid     a string that uniquely identifies this Sink
     */
    public function __construct(Version $version, string $sid)
    {
        parent::__construct($version);

        // Path Solution
        $this->solution = ['sid' => $sid];

        $this->uri = '/Sinks/'.\rawurlencode($sid).'/Test';
    }

    /**
     * Provide a friendly representation.
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string
    {
        return '[Twilio.Events.V1.SinkTestList]';
    }

    /**
     * Create the SinkTestInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return SinkTestInstance Created SinkTestInstance
     */
    public function create(): SinkTestInstance
    {
        $payload = $this->version->create('POST', $this->uri);

        return new SinkTestInstance($this->version, $payload, $this->solution['sid']);
    }
}
