<?php

declare(strict_types=1);

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0.
 * /       /
 */

namespace Twilio\Rest\Conversations\V1;

use Twilio\Exceptions\TwilioException;
use Twilio\InstanceContext;
use Twilio\Options;
use Twilio\Values;
use Twilio\Version;

class ConfigurationContext extends InstanceContext
{
    /**
     * Initialize the ConfigurationContext.
     *
     * @param Version $version Version that contains the resource
     */
    public function __construct(Version $version)
    {
        parent::__construct($version);

        // Path Solution
        $this->solution = [];

        $this->uri = '/Configuration';
    }

    /**
     * Provide a friendly representation.
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string
    {
        $context = [];
        foreach ($this->solution as $key => $value) {
            $context[] = "{$key}={$value}";
        }

        return '[Twilio.Conversations.V1.ConfigurationContext '.\implode(' ', $context).']';
    }

    /**
     * Fetch the ConfigurationInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return ConfigurationInstance Fetched ConfigurationInstance
     */
    public function fetch(): ConfigurationInstance
    {
        $payload = $this->version->fetch('GET', $this->uri);

        return new ConfigurationInstance($this->version, $payload);
    }

    /**
     * Update the ConfigurationInstance.
     *
     * @param array|Options $options Optional Arguments
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return ConfigurationInstance Updated ConfigurationInstance
     */
    public function update(array $options = []): ConfigurationInstance
    {
        $options = new Values($options);

        $data = Values::of([
            'DefaultChatServiceSid' => $options['defaultChatServiceSid'],
            'DefaultMessagingServiceSid' => $options['defaultMessagingServiceSid'],
            'DefaultInactiveTimer' => $options['defaultInactiveTimer'],
            'DefaultClosedTimer' => $options['defaultClosedTimer'],
        ]);

        $payload = $this->version->update('POST', $this->uri, [], $data);

        return new ConfigurationInstance($this->version, $payload);
    }
}
