<?php

declare(strict_types=1);

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0.
 * /       /
 */

namespace Twilio\Rest\Voice\V1;

use Twilio\Deserialize;
use Twilio\Exceptions\TwilioException;
use Twilio\InstanceResource;
use Twilio\Values;
use Twilio\Version;

/**
 * @property string    $sid
 * @property string    $ipRecordSid
 * @property string    $sipDomainSid
 * @property \DateTime $dateCreated
 * @property \DateTime $dateUpdated
 * @property string    $url
 */
class SourceIpMappingInstance extends InstanceResource
{
    /**
     * Initialize the SourceIpMappingInstance.
     *
     * @param Version $version Version that contains the resource
     * @param mixed[] $payload The response payload
     * @param string  $sid     The unique string that identifies the resource
     */
    public function __construct(Version $version, array $payload, string $sid = null)
    {
        parent::__construct($version);

        // Marshaled Properties
        $this->properties = [
            'sid' => Values::array_get($payload, 'sid'),
            'ipRecordSid' => Values::array_get($payload, 'ip_record_sid'),
            'sipDomainSid' => Values::array_get($payload, 'sip_domain_sid'),
            'dateCreated' => Deserialize::dateTime(Values::array_get($payload, 'date_created')),
            'dateUpdated' => Deserialize::dateTime(Values::array_get($payload, 'date_updated')),
            'url' => Values::array_get($payload, 'url'),
        ];

        $this->solution = ['sid' => $sid ?: $this->properties['sid']];
    }

    /**
     * Magic getter to access properties.
     *
     * @param string $name Property to access
     *
     * @throws TwilioException For unknown properties
     *
     * @return mixed The requested property
     */
    public function __get(string $name)
    {
        if (\array_key_exists($name, $this->properties)) {
            return $this->properties[$name];
        }

        if (\property_exists($this, '_'.$name)) {
            $method = 'get'.\ucfirst($name);

            return $this->{$method}();
        }

        throw new TwilioException('Unknown property: '.$name);
    }

    /**
     * Provide a friendly representation.
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string
    {
        $context = [];
        foreach ($this->solution as $key => $value) {
            $context[] = "{$key}={$value}";
        }

        return '[Twilio.Voice.V1.SourceIpMappingInstance '.\implode(' ', $context).']';
    }

    /**
     * Fetch the SourceIpMappingInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return SourceIpMappingInstance Fetched SourceIpMappingInstance
     */
    public function fetch(): SourceIpMappingInstance
    {
        return $this->proxy()->fetch();
    }

    /**
     * Update the SourceIpMappingInstance.
     *
     * @param string $sipDomainSid The unique string that identifies a SIP Domain
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return SourceIpMappingInstance Updated SourceIpMappingInstance
     */
    public function update(string $sipDomainSid): SourceIpMappingInstance
    {
        return $this->proxy()->update($sipDomainSid);
    }

    /**
     * Delete the SourceIpMappingInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return bool True if delete succeeds, false otherwise
     */
    public function delete(): bool
    {
        return $this->proxy()->delete();
    }

    /**
     * Generate an instance context for the instance, the context is capable of
     * performing various actions.  All instance actions are proxied to the context.
     *
     * @return SourceIpMappingContext Context for this SourceIpMappingInstance
     */
    protected function proxy(): SourceIpMappingContext
    {
        if (!$this->context) {
            $this->context = new SourceIpMappingContext($this->version, $this->solution['sid']);
        }

        return $this->context;
    }
}
