<?php

declare(strict_types=1);

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0.
 * /       /
 */

namespace Twilio\Rest\Video\V1;

use Twilio\Exceptions\TwilioException;
use Twilio\InstanceContext;
use Twilio\Version;

class RecordingContext extends InstanceContext
{
    /**
     * Initialize the RecordingContext.
     *
     * @param Version $version Version that contains the resource
     * @param string  $sid     The SID that identifies the resource to fetch
     */
    public function __construct(Version $version, $sid)
    {
        parent::__construct($version);

        // Path Solution
        $this->solution = ['sid' => $sid];

        $this->uri = '/Recordings/'.\rawurlencode($sid).'';
    }

    /**
     * Provide a friendly representation.
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string
    {
        $context = [];
        foreach ($this->solution as $key => $value) {
            $context[] = "{$key}={$value}";
        }

        return '[Twilio.Video.V1.RecordingContext '.\implode(' ', $context).']';
    }

    /**
     * Fetch the RecordingInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return RecordingInstance Fetched RecordingInstance
     */
    public function fetch(): RecordingInstance
    {
        $payload = $this->version->fetch('GET', $this->uri);

        return new RecordingInstance($this->version, $payload, $this->solution['sid']);
    }

    /**
     * Delete the RecordingInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return bool True if delete succeeds, false otherwise
     */
    public function delete(): bool
    {
        return $this->version->delete('DELETE', $this->uri);
    }
}
