<?php

declare(strict_types=1);

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0.
 * /       /
 */

namespace Twilio\Rest\Api\V2010\Account;

use Twilio\Exceptions\TwilioException;
use Twilio\ListResource;
use Twilio\Version;

class BalanceList extends ListResource
{
    /**
     * Construct the BalanceList.
     *
     * @param Version $version    Version that contains the resource
     * @param string  $accountSid account Sid
     */
    public function __construct(Version $version, string $accountSid)
    {
        parent::__construct($version);

        // Path Solution
        $this->solution = ['accountSid' => $accountSid];

        $this->uri = '/Accounts/'.\rawurlencode($accountSid).'/Balance.json';
    }

    /**
     * Provide a friendly representation.
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string
    {
        return '[Twilio.Api.V2010.BalanceList]';
    }

    /**
     * Fetch the BalanceInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return BalanceInstance Fetched BalanceInstance
     */
    public function fetch(): BalanceInstance
    {
        $payload = $this->version->fetch('GET', $this->uri);

        return new BalanceInstance($this->version, $payload, $this->solution['accountSid']);
    }
}
