<?php

declare(strict_types=1);

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0.
 * /       /
 */

namespace Twilio\Rest\Api\V2010\Account;

use Twilio\Deserialize;
use Twilio\Exceptions\TwilioException;
use Twilio\InstanceResource;
use Twilio\Options;
use Twilio\Values;
use Twilio\Version;

/**
 * @property string    $sid
 * @property \DateTime $dateCreated
 * @property \DateTime $dateUpdated
 * @property string    $friendlyName
 * @property string    $accountSid
 * @property string    $phoneNumber
 * @property string    $uri
 */
class OutgoingCallerIdInstance extends InstanceResource
{
    /**
     * Initialize the OutgoingCallerIdInstance.
     *
     * @param Version $version    Version that contains the resource
     * @param mixed[] $payload    The response payload
     * @param string  $accountSid The SID of the Account that created the resource
     * @param string  $sid        The unique string that identifies the resource
     */
    public function __construct(Version $version, array $payload, string $accountSid, string $sid = null)
    {
        parent::__construct($version);

        // Marshaled Properties
        $this->properties = [
            'sid' => Values::array_get($payload, 'sid'),
            'dateCreated' => Deserialize::dateTime(Values::array_get($payload, 'date_created')),
            'dateUpdated' => Deserialize::dateTime(Values::array_get($payload, 'date_updated')),
            'friendlyName' => Values::array_get($payload, 'friendly_name'),
            'accountSid' => Values::array_get($payload, 'account_sid'),
            'phoneNumber' => Values::array_get($payload, 'phone_number'),
            'uri' => Values::array_get($payload, 'uri'),
        ];

        $this->solution = ['accountSid' => $accountSid, 'sid' => $sid ?: $this->properties['sid']];
    }

    /**
     * Magic getter to access properties.
     *
     * @param string $name Property to access
     *
     * @throws TwilioException For unknown properties
     *
     * @return mixed The requested property
     */
    public function __get(string $name)
    {
        if (\array_key_exists($name, $this->properties)) {
            return $this->properties[$name];
        }

        if (\property_exists($this, '_'.$name)) {
            $method = 'get'.\ucfirst($name);

            return $this->{$method}();
        }

        throw new TwilioException('Unknown property: '.$name);
    }

    /**
     * Provide a friendly representation.
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string
    {
        $context = [];
        foreach ($this->solution as $key => $value) {
            $context[] = "{$key}={$value}";
        }

        return '[Twilio.Api.V2010.OutgoingCallerIdInstance '.\implode(' ', $context).']';
    }

    /**
     * Fetch the OutgoingCallerIdInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return OutgoingCallerIdInstance Fetched OutgoingCallerIdInstance
     */
    public function fetch(): OutgoingCallerIdInstance
    {
        return $this->proxy()->fetch();
    }

    /**
     * Update the OutgoingCallerIdInstance.
     *
     * @param array|Options $options Optional Arguments
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return OutgoingCallerIdInstance Updated OutgoingCallerIdInstance
     */
    public function update(array $options = []): OutgoingCallerIdInstance
    {
        return $this->proxy()->update($options);
    }

    /**
     * Delete the OutgoingCallerIdInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return bool True if delete succeeds, false otherwise
     */
    public function delete(): bool
    {
        return $this->proxy()->delete();
    }

    /**
     * Generate an instance context for the instance, the context is capable of
     * performing various actions.  All instance actions are proxied to the context.
     *
     * @return OutgoingCallerIdContext Context for this OutgoingCallerIdInstance
     */
    protected function proxy(): OutgoingCallerIdContext
    {
        if (!$this->context) {
            $this->context = new OutgoingCallerIdContext(
                $this->version,
                $this->solution['accountSid'],
                $this->solution['sid']
            );
        }

        return $this->context;
    }
}
