<?php

declare(strict_types=1);

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0.
 * /       /
 */

namespace Twilio\Rest\Trusthub\V1\TrustProducts;

use Twilio\Deserialize;
use Twilio\Exceptions\TwilioException;
use Twilio\InstanceResource;
use Twilio\Values;
use Twilio\Version;

/**
 * @property string    $sid
 * @property string    $accountSid
 * @property string    $policySid
 * @property string    $trustProductSid
 * @property string    $status
 * @property array[]   $results
 * @property \DateTime $dateCreated
 * @property string    $url
 */
class TrustProductsEvaluationsInstance extends InstanceResource
{
    /**
     * Initialize the TrustProductsEvaluationsInstance.
     *
     * @param Version $version         Version that contains the resource
     * @param mixed[] $payload         The response payload
     * @param string  $trustProductSid The unique string that identifies the resource
     * @param string  $sid             The unique string that identifies the Evaluation resource
     */
    public function __construct(Version $version, array $payload, string $trustProductSid, string $sid = null)
    {
        parent::__construct($version);

        // Marshaled Properties
        $this->properties = [
            'sid' => Values::array_get($payload, 'sid'),
            'accountSid' => Values::array_get($payload, 'account_sid'),
            'policySid' => Values::array_get($payload, 'policy_sid'),
            'trustProductSid' => Values::array_get($payload, 'trust_product_sid'),
            'status' => Values::array_get($payload, 'status'),
            'results' => Values::array_get($payload, 'results'),
            'dateCreated' => Deserialize::dateTime(Values::array_get($payload, 'date_created')),
            'url' => Values::array_get($payload, 'url'),
        ];

        $this->solution = [
            'trustProductSid' => $trustProductSid,
            'sid' => $sid ?: $this->properties['sid'],
        ];
    }

    /**
     * Magic getter to access properties.
     *
     * @param string $name Property to access
     *
     * @throws TwilioException For unknown properties
     *
     * @return mixed The requested property
     */
    public function __get(string $name)
    {
        if (\array_key_exists($name, $this->properties)) {
            return $this->properties[$name];
        }

        if (\property_exists($this, '_'.$name)) {
            $method = 'get'.\ucfirst($name);

            return $this->{$method}();
        }

        throw new TwilioException('Unknown property: '.$name);
    }

    /**
     * Provide a friendly representation.
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string
    {
        $context = [];
        foreach ($this->solution as $key => $value) {
            $context[] = "{$key}={$value}";
        }

        return '[Twilio.Trusthub.V1.TrustProductsEvaluationsInstance '.\implode(' ', $context).']';
    }

    /**
     * Fetch the TrustProductsEvaluationsInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return TrustProductsEvaluationsInstance Fetched
     *                                          TrustProductsEvaluationsInstance
     */
    public function fetch(): TrustProductsEvaluationsInstance
    {
        return $this->proxy()->fetch();
    }

    /**
     * Generate an instance context for the instance, the context is capable of
     * performing various actions.  All instance actions are proxied to the context.
     *
     * @return TrustProductsEvaluationsContext Context for this
     *                                         TrustProductsEvaluationsInstance
     */
    protected function proxy(): TrustProductsEvaluationsContext
    {
        if (!$this->context) {
            $this->context = new TrustProductsEvaluationsContext(
                $this->version,
                $this->solution['trustProductSid'],
                $this->solution['sid']
            );
        }

        return $this->context;
    }
}
