<?php

declare(strict_types=1);

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0.
 * /       /
 */

namespace Twilio\Rest\Api\V2010\Account\Sip\Domain\AuthTypes\AuthTypeCalls;

use Twilio\Exceptions\TwilioException;
use Twilio\InstanceContext;
use Twilio\Version;

class AuthCallsCredentialListMappingContext extends InstanceContext
{
    /**
     * Initialize the AuthCallsCredentialListMappingContext.
     *
     * @param Version $version    Version that contains the resource
     * @param string  $accountSid The SID of the Account that created the resource
     *                            to fetch
     * @param string  $domainSid  The SID of the SIP domain that contains the
     *                            resource to fetch
     * @param string  $sid        The unique string that identifies the resource
     */
    public function __construct(Version $version, $accountSid, $domainSid, $sid)
    {
        parent::__construct($version);

        // Path Solution
        $this->solution = ['accountSid' => $accountSid, 'domainSid' => $domainSid, 'sid' => $sid];

        $this->uri = '/Accounts/'.\rawurlencode($accountSid).'/SIP/Domains/'.\rawurlencode($domainSid).'/Auth/Calls/CredentialListMappings/'.\rawurlencode($sid).'.json';
    }

    /**
     * Provide a friendly representation.
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string
    {
        $context = [];
        foreach ($this->solution as $key => $value) {
            $context[] = "{$key}={$value}";
        }

        return '[Twilio.Api.V2010.AuthCallsCredentialListMappingContext '.\implode(' ', $context).']';
    }

    /**
     * Fetch the AuthCallsCredentialListMappingInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return AuthCallsCredentialListMappingInstance Fetched
     *                                                AuthCallsCredentialListMappingInstance
     */
    public function fetch(): AuthCallsCredentialListMappingInstance
    {
        $payload = $this->version->fetch('GET', $this->uri);

        return new AuthCallsCredentialListMappingInstance(
            $this->version,
            $payload,
            $this->solution['accountSid'],
            $this->solution['domainSid'],
            $this->solution['sid']
        );
    }

    /**
     * Delete the AuthCallsCredentialListMappingInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return bool True if delete succeeds, false otherwise
     */
    public function delete(): bool
    {
        return $this->version->delete('DELETE', $this->uri);
    }
}
