<?php

declare(strict_types=1);

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0.
 * /       /
 */

namespace Twilio\Rest\Wireless\V1;

use Twilio\Exceptions\TwilioException;
use Twilio\InstanceContext;
use Twilio\Options;
use Twilio\Values;
use Twilio\Version;

class RatePlanContext extends InstanceContext
{
    /**
     * Initialize the RatePlanContext.
     *
     * @param Version $version Version that contains the resource
     * @param string  $sid     The SID that identifies the resource to fetch
     */
    public function __construct(Version $version, $sid)
    {
        parent::__construct($version);

        // Path Solution
        $this->solution = ['sid' => $sid];

        $this->uri = '/RatePlans/'.\rawurlencode($sid).'';
    }

    /**
     * Provide a friendly representation.
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string
    {
        $context = [];
        foreach ($this->solution as $key => $value) {
            $context[] = "{$key}={$value}";
        }

        return '[Twilio.Wireless.V1.RatePlanContext '.\implode(' ', $context).']';
    }

    /**
     * Fetch the RatePlanInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return RatePlanInstance Fetched RatePlanInstance
     */
    public function fetch(): RatePlanInstance
    {
        $payload = $this->version->fetch('GET', $this->uri);

        return new RatePlanInstance($this->version, $payload, $this->solution['sid']);
    }

    /**
     * Update the RatePlanInstance.
     *
     * @param array|Options $options Optional Arguments
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return RatePlanInstance Updated RatePlanInstance
     */
    public function update(array $options = []): RatePlanInstance
    {
        $options = new Values($options);

        $data = Values::of([
            'UniqueName' => $options['uniqueName'],
            'FriendlyName' => $options['friendlyName'],
        ]);

        $payload = $this->version->update('POST', $this->uri, [], $data);

        return new RatePlanInstance($this->version, $payload, $this->solution['sid']);
    }

    /**
     * Delete the RatePlanInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return bool True if delete succeeds, false otherwise
     */
    public function delete(): bool
    {
        return $this->version->delete('DELETE', $this->uri);
    }
}
