<?php

declare(strict_types=1);

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0.
 * /       /
 */

namespace Twilio\Rest\Autopilot\V1\Assistant;

use Twilio\Exceptions\TwilioException;
use Twilio\InstanceContext;
use Twilio\Options;
use Twilio\Serialize;
use Twilio\Values;
use Twilio\Version;

/**
 * PLEASE NOTE that this class contains preview products that are subject to change. Use them with caution. If you currently do not have developer preview access, please contact help@twilio.com.
 */
class DefaultsContext extends InstanceContext
{
    /**
     * Initialize the DefaultsContext.
     *
     * @param Version $version      Version that contains the resource
     * @param string  $assistantSid The SID of the Assistant that is the parent of
     *                              the resource to fetch
     */
    public function __construct(Version $version, $assistantSid)
    {
        parent::__construct($version);

        // Path Solution
        $this->solution = ['assistantSid' => $assistantSid];

        $this->uri = '/Assistants/'.\rawurlencode($assistantSid).'/Defaults';
    }

    /**
     * Provide a friendly representation.
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string
    {
        $context = [];
        foreach ($this->solution as $key => $value) {
            $context[] = "{$key}={$value}";
        }

        return '[Twilio.Autopilot.V1.DefaultsContext '.\implode(' ', $context).']';
    }

    /**
     * Fetch the DefaultsInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return DefaultsInstance Fetched DefaultsInstance
     */
    public function fetch(): DefaultsInstance
    {
        $payload = $this->version->fetch('GET', $this->uri);

        return new DefaultsInstance($this->version, $payload, $this->solution['assistantSid']);
    }

    /**
     * Update the DefaultsInstance.
     *
     * @param array|Options $options Optional Arguments
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return DefaultsInstance Updated DefaultsInstance
     */
    public function update(array $options = []): DefaultsInstance
    {
        $options = new Values($options);

        $data = Values::of(['Defaults' => Serialize::jsonObject($options['defaults'])]);

        $payload = $this->version->update('POST', $this->uri, [], $data);

        return new DefaultsInstance($this->version, $payload, $this->solution['assistantSid']);
    }
}
