<?php

declare(strict_types=1);

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0.
 * /       /
 */

namespace Twilio\Rest\Insights\V1;

use Twilio\Exceptions\TwilioException;
use Twilio\InstanceContext;
use Twilio\ListResource;
use Twilio\Rest\Insights\V1\Room\ParticipantList;
use Twilio\Version;

/**
 * PLEASE NOTE that this class contains beta products that are subject to change. Use them with caution.
 *
 * @property ParticipantList $participants
 *
 * @method \Twilio\Rest\Insights\V1\Room\ParticipantContext participants(string $participantSid)
 */
class RoomContext extends InstanceContext
{
    protected $_participants;

    /**
     * Initialize the RoomContext.
     *
     * @param Version $version Version that contains the resource
     * @param string  $roomSid the SID of the Room resource
     */
    public function __construct(Version $version, $roomSid)
    {
        parent::__construct($version);

        // Path Solution
        $this->solution = ['roomSid' => $roomSid];

        $this->uri = '/Video/Rooms/'.\rawurlencode($roomSid).'';
    }

    /**
     * Magic getter to lazy load subresources.
     *
     * @param string $name Subresource to return
     *
     * @throws TwilioException For unknown subresources
     *
     * @return ListResource The requested subresource
     */
    public function __get(string $name): ListResource
    {
        if (\property_exists($this, '_'.$name)) {
            $method = 'get'.\ucfirst($name);

            return $this->{$method}();
        }

        throw new TwilioException('Unknown subresource '.$name);
    }

    /**
     * Magic caller to get resource contexts.
     *
     * @param string $name      Resource to return
     * @param array  $arguments Context parameters
     *
     * @throws TwilioException For unknown resource
     *
     * @return InstanceContext The requested resource context
     */
    public function __call(string $name, array $arguments): InstanceContext
    {
        $property = $this->{$name};
        if (\method_exists($property, 'getContext')) {
            return \call_user_func_array([$property, 'getContext'], $arguments);
        }

        throw new TwilioException('Resource does not have a context');
    }

    /**
     * Provide a friendly representation.
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string
    {
        $context = [];
        foreach ($this->solution as $key => $value) {
            $context[] = "{$key}={$value}";
        }

        return '[Twilio.Insights.V1.RoomContext '.\implode(' ', $context).']';
    }

    /**
     * Fetch the RoomInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return RoomInstance Fetched RoomInstance
     */
    public function fetch(): RoomInstance
    {
        $payload = $this->version->fetch('GET', $this->uri);

        return new RoomInstance($this->version, $payload, $this->solution['roomSid']);
    }

    /**
     * Access the participants.
     */
    protected function getParticipants(): ParticipantList
    {
        if (!$this->_participants) {
            $this->_participants = new ParticipantList($this->version, $this->solution['roomSid']);
        }

        return $this->_participants;
    }
}
