<?php

declare(strict_types=1);

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0.
 * /       /
 */

namespace Twilio\Rest\Studio\V2\Flow;

use Twilio\Exceptions\TwilioException;
use Twilio\InstanceContext;
use Twilio\Serialize;
use Twilio\Values;
use Twilio\Version;

class FlowTestUserContext extends InstanceContext
{
    /**
     * Initialize the FlowTestUserContext.
     *
     * @param Version $version Version that contains the resource
     * @param string  $sid     unique identifier of the flow
     */
    public function __construct(Version $version, $sid)
    {
        parent::__construct($version);

        // Path Solution
        $this->solution = ['sid' => $sid];

        $this->uri = '/Flows/'.\rawurlencode($sid).'/TestUsers';
    }

    /**
     * Provide a friendly representation.
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string
    {
        $context = [];
        foreach ($this->solution as $key => $value) {
            $context[] = "{$key}={$value}";
        }

        return '[Twilio.Studio.V2.FlowTestUserContext '.\implode(' ', $context).']';
    }

    /**
     * Fetch the FlowTestUserInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return FlowTestUserInstance Fetched FlowTestUserInstance
     */
    public function fetch(): FlowTestUserInstance
    {
        $payload = $this->version->fetch('GET', $this->uri);

        return new FlowTestUserInstance($this->version, $payload, $this->solution['sid']);
    }

    /**
     * Update the FlowTestUserInstance.
     *
     * @param string[] $testUsers list of test user identities that can test draft
     *                            versions of the flow
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return FlowTestUserInstance Updated FlowTestUserInstance
     */
    public function update(array $testUsers): FlowTestUserInstance
    {
        $data = Values::of(['TestUsers' => Serialize::map($testUsers, fn ($e) => $e)]);

        $payload = $this->version->update('POST', $this->uri, [], $data);

        return new FlowTestUserInstance($this->version, $payload, $this->solution['sid']);
    }
}
