<?php

declare(strict_types=1);

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0.
 * /       /
 */

namespace Twilio\Rest\Chat\V2\Service\Channel;

use Twilio\Exceptions\TwilioException;
use Twilio\InstanceContext;
use Twilio\Version;

class InviteContext extends InstanceContext
{
    /**
     * Initialize the InviteContext.
     *
     * @param Version $version    Version that contains the resource
     * @param string  $serviceSid The SID of the Service to fetch the resource from
     * @param string  $channelSid The SID of the Channel the resource to fetch
     *                            belongs to
     * @param string  $sid        The SID of the Invite resource to fetch
     */
    public function __construct(Version $version, $serviceSid, $channelSid, $sid)
    {
        parent::__construct($version);

        // Path Solution
        $this->solution = ['serviceSid' => $serviceSid, 'channelSid' => $channelSid, 'sid' => $sid];

        $this->uri = '/Services/'.\rawurlencode($serviceSid).'/Channels/'.\rawurlencode($channelSid).'/Invites/'.\rawurlencode($sid).'';
    }

    /**
     * Provide a friendly representation.
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string
    {
        $context = [];
        foreach ($this->solution as $key => $value) {
            $context[] = "{$key}={$value}";
        }

        return '[Twilio.Chat.V2.InviteContext '.\implode(' ', $context).']';
    }

    /**
     * Fetch the InviteInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return InviteInstance Fetched InviteInstance
     */
    public function fetch(): InviteInstance
    {
        $payload = $this->version->fetch('GET', $this->uri);

        return new InviteInstance(
            $this->version,
            $payload,
            $this->solution['serviceSid'],
            $this->solution['channelSid'],
            $this->solution['sid']
        );
    }

    /**
     * Delete the InviteInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return bool True if delete succeeds, false otherwise
     */
    public function delete(): bool
    {
        return $this->version->delete('DELETE', $this->uri);
    }
}
