<?php

declare(strict_types=1);

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0.
 * /       /
 */

namespace Twilio\Rest\Preview\BulkExports\Export;

use Twilio\Exceptions\TwilioException;
use Twilio\InstanceContext;
use Twilio\Version;

/**
 * PLEASE NOTE that this class contains preview products that are subject to change. Use them with caution. If you currently do not have developer preview access, please contact help@twilio.com.
 */
class JobContext extends InstanceContext
{
    /**
     * Initialize the JobContext.
     *
     * @param Version $version Version that contains the resource
     * @param string  $jobSid  The unique string that that we created to identify the
     *                         Bulk Export job
     */
    public function __construct(Version $version, $jobSid)
    {
        parent::__construct($version);

        // Path Solution
        $this->solution = ['jobSid' => $jobSid];

        $this->uri = '/Exports/Jobs/'.\rawurlencode($jobSid).'';
    }

    /**
     * Provide a friendly representation.
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string
    {
        $context = [];
        foreach ($this->solution as $key => $value) {
            $context[] = "{$key}={$value}";
        }

        return '[Twilio.Preview.BulkExports.JobContext '.\implode(' ', $context).']';
    }

    /**
     * Fetch the JobInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return JobInstance Fetched JobInstance
     */
    public function fetch(): JobInstance
    {
        $payload = $this->version->fetch('GET', $this->uri);

        return new JobInstance($this->version, $payload, $this->solution['jobSid']);
    }

    /**
     * Delete the JobInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return bool True if delete succeeds, false otherwise
     */
    public function delete(): bool
    {
        return $this->version->delete('DELETE', $this->uri);
    }
}
