<?php

declare(strict_types=1);

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0.
 * /       /
 */

namespace Twilio\Rest\Trusthub\V1;

use Twilio\Deserialize;
use Twilio\Exceptions\TwilioException;
use Twilio\InstanceResource;
use Twilio\Options;
use Twilio\Rest\Trusthub\V1\CustomerProfiles\CustomerProfilesChannelEndpointAssignmentList;
use Twilio\Rest\Trusthub\V1\CustomerProfiles\CustomerProfilesEntityAssignmentsList;
use Twilio\Rest\Trusthub\V1\CustomerProfiles\CustomerProfilesEvaluationsList;
use Twilio\Values;
use Twilio\Version;

/**
 * @property string    $sid
 * @property string    $accountSid
 * @property string    $policySid
 * @property string    $friendlyName
 * @property string    $status
 * @property \DateTime $validUntil
 * @property string    $email
 * @property string    $statusCallback
 * @property \DateTime $dateCreated
 * @property \DateTime $dateUpdated
 * @property string    $url
 * @property array     $links
 */
class CustomerProfilesInstance extends InstanceResource
{
    protected $_customerProfilesEntityAssignments;
    protected $_customerProfilesEvaluations;
    protected $_customerProfilesChannelEndpointAssignment;

    /**
     * Initialize the CustomerProfilesInstance.
     *
     * @param Version $version Version that contains the resource
     * @param mixed[] $payload The response payload
     * @param string  $sid     the unique string that identifies the resource
     */
    public function __construct(Version $version, array $payload, string $sid = null)
    {
        parent::__construct($version);

        // Marshaled Properties
        $this->properties = [
            'sid' => Values::array_get($payload, 'sid'),
            'accountSid' => Values::array_get($payload, 'account_sid'),
            'policySid' => Values::array_get($payload, 'policy_sid'),
            'friendlyName' => Values::array_get($payload, 'friendly_name'),
            'status' => Values::array_get($payload, 'status'),
            'validUntil' => Deserialize::dateTime(Values::array_get($payload, 'valid_until')),
            'email' => Values::array_get($payload, 'email'),
            'statusCallback' => Values::array_get($payload, 'status_callback'),
            'dateCreated' => Deserialize::dateTime(Values::array_get($payload, 'date_created')),
            'dateUpdated' => Deserialize::dateTime(Values::array_get($payload, 'date_updated')),
            'url' => Values::array_get($payload, 'url'),
            'links' => Values::array_get($payload, 'links'),
        ];

        $this->solution = ['sid' => $sid ?: $this->properties['sid']];
    }

    /**
     * Magic getter to access properties.
     *
     * @param string $name Property to access
     *
     * @throws TwilioException For unknown properties
     *
     * @return mixed The requested property
     */
    public function __get(string $name)
    {
        if (\array_key_exists($name, $this->properties)) {
            return $this->properties[$name];
        }

        if (\property_exists($this, '_'.$name)) {
            $method = 'get'.\ucfirst($name);

            return $this->{$method}();
        }

        throw new TwilioException('Unknown property: '.$name);
    }

    /**
     * Provide a friendly representation.
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string
    {
        $context = [];
        foreach ($this->solution as $key => $value) {
            $context[] = "{$key}={$value}";
        }

        return '[Twilio.Trusthub.V1.CustomerProfilesInstance '.\implode(' ', $context).']';
    }

    /**
     * Fetch the CustomerProfilesInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return CustomerProfilesInstance Fetched CustomerProfilesInstance
     */
    public function fetch(): CustomerProfilesInstance
    {
        return $this->proxy()->fetch();
    }

    /**
     * Update the CustomerProfilesInstance.
     *
     * @param array|Options $options Optional Arguments
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return CustomerProfilesInstance Updated CustomerProfilesInstance
     */
    public function update(array $options = []): CustomerProfilesInstance
    {
        return $this->proxy()->update($options);
    }

    /**
     * Delete the CustomerProfilesInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return bool True if delete succeeds, false otherwise
     */
    public function delete(): bool
    {
        return $this->proxy()->delete();
    }

    /**
     * Generate an instance context for the instance, the context is capable of
     * performing various actions.  All instance actions are proxied to the context.
     *
     * @return CustomerProfilesContext Context for this CustomerProfilesInstance
     */
    protected function proxy(): CustomerProfilesContext
    {
        if (!$this->context) {
            $this->context = new CustomerProfilesContext($this->version, $this->solution['sid']);
        }

        return $this->context;
    }

    /**
     * Access the customerProfilesEntityAssignments.
     */
    protected function getCustomerProfilesEntityAssignments(): CustomerProfilesEntityAssignmentsList
    {
        return $this->proxy()->customerProfilesEntityAssignments;
    }

    /**
     * Access the customerProfilesEvaluations.
     */
    protected function getCustomerProfilesEvaluations(): CustomerProfilesEvaluationsList
    {
        return $this->proxy()->customerProfilesEvaluations;
    }

    /**
     * Access the customerProfilesChannelEndpointAssignment.
     */
    protected function getCustomerProfilesChannelEndpointAssignment(): CustomerProfilesChannelEndpointAssignmentList
    {
        return $this->proxy()->customerProfilesChannelEndpointAssignment;
    }
}
