<?php

declare(strict_types=1);

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0.
 * /       /
 */

namespace Twilio\Rest\Trunking\V1\Trunk;

use Twilio\Exceptions\TwilioException;
use Twilio\InstanceContext;
use Twilio\Version;

class CredentialListContext extends InstanceContext
{
    /**
     * Initialize the CredentialListContext.
     *
     * @param Version $version  Version that contains the resource
     * @param string  $trunkSid The SID of the Trunk from which to fetch the
     *                          credential list
     * @param string  $sid      The unique string that identifies the resource
     */
    public function __construct(Version $version, $trunkSid, $sid)
    {
        parent::__construct($version);

        // Path Solution
        $this->solution = ['trunkSid' => $trunkSid, 'sid' => $sid];

        $this->uri = '/Trunks/'.\rawurlencode($trunkSid).'/CredentialLists/'.\rawurlencode($sid).'';
    }

    /**
     * Provide a friendly representation.
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string
    {
        $context = [];
        foreach ($this->solution as $key => $value) {
            $context[] = "{$key}={$value}";
        }

        return '[Twilio.Trunking.V1.CredentialListContext '.\implode(' ', $context).']';
    }

    /**
     * Fetch the CredentialListInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return CredentialListInstance Fetched CredentialListInstance
     */
    public function fetch(): CredentialListInstance
    {
        $payload = $this->version->fetch('GET', $this->uri);

        return new CredentialListInstance(
            $this->version,
            $payload,
            $this->solution['trunkSid'],
            $this->solution['sid']
        );
    }

    /**
     * Delete the CredentialListInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return bool True if delete succeeds, false otherwise
     */
    public function delete(): bool
    {
        return $this->version->delete('DELETE', $this->uri);
    }
}
