<?php

declare(strict_types=1);

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0.
 * /       /
 */

namespace Twilio\Rest\Trunking\V1\Trunk;

use Twilio\Exceptions\TwilioException;
use Twilio\InstanceContext;
use Twilio\Options;
use Twilio\Serialize;
use Twilio\Values;
use Twilio\Version;

class OriginationUrlContext extends InstanceContext
{
    /**
     * Initialize the OriginationUrlContext.
     *
     * @param Version $version  Version that contains the resource
     * @param string  $trunkSid The SID of the Trunk from which to fetch the
     *                          OriginationUrl
     * @param string  $sid      The unique string that identifies the resource
     */
    public function __construct(Version $version, $trunkSid, $sid)
    {
        parent::__construct($version);

        // Path Solution
        $this->solution = ['trunkSid' => $trunkSid, 'sid' => $sid];

        $this->uri = '/Trunks/'.\rawurlencode($trunkSid).'/OriginationUrls/'.\rawurlencode($sid).'';
    }

    /**
     * Provide a friendly representation.
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string
    {
        $context = [];
        foreach ($this->solution as $key => $value) {
            $context[] = "{$key}={$value}";
        }

        return '[Twilio.Trunking.V1.OriginationUrlContext '.\implode(' ', $context).']';
    }

    /**
     * Fetch the OriginationUrlInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return OriginationUrlInstance Fetched OriginationUrlInstance
     */
    public function fetch(): OriginationUrlInstance
    {
        $payload = $this->version->fetch('GET', $this->uri);

        return new OriginationUrlInstance(
            $this->version,
            $payload,
            $this->solution['trunkSid'],
            $this->solution['sid']
        );
    }

    /**
     * Delete the OriginationUrlInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return bool True if delete succeeds, false otherwise
     */
    public function delete(): bool
    {
        return $this->version->delete('DELETE', $this->uri);
    }

    /**
     * Update the OriginationUrlInstance.
     *
     * @param array|Options $options Optional Arguments
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return OriginationUrlInstance Updated OriginationUrlInstance
     */
    public function update(array $options = []): OriginationUrlInstance
    {
        $options = new Values($options);

        $data = Values::of([
            'Weight' => $options['weight'],
            'Priority' => $options['priority'],
            'Enabled' => Serialize::booleanToString($options['enabled']),
            'FriendlyName' => $options['friendlyName'],
            'SipUrl' => $options['sipUrl'],
        ]);

        $payload = $this->version->update('POST', $this->uri, [], $data);

        return new OriginationUrlInstance(
            $this->version,
            $payload,
            $this->solution['trunkSid'],
            $this->solution['sid']
        );
    }
}
