<?php

declare(strict_types=1);

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0.
 * /       /
 */

namespace Twilio\Rest;

use Twilio\Domain;
use Twilio\Exceptions\TwilioException;
use Twilio\Rest\FlexApi\V1;

/**
 * @property \Twilio\Rest\FlexApi\V1                   $v1
 * @property \Twilio\Rest\FlexApi\V1\ChannelList       $channel
 * @property \Twilio\Rest\FlexApi\V1\ConfigurationList $configuration
 * @property \Twilio\Rest\FlexApi\V1\FlexFlowList      $flexFlow
 * @property \Twilio\Rest\FlexApi\V1\WebChannelList    $webChannel
 *
 * @method \Twilio\Rest\FlexApi\V1\ChannelContext       channel(string $sid)
 * @method \Twilio\Rest\FlexApi\V1\ConfigurationContext configuration()
 * @method \Twilio\Rest\FlexApi\V1\FlexFlowContext      flexFlow(string $sid)
 * @method \Twilio\Rest\FlexApi\V1\WebChannelContext    webChannel(string $sid)
 */
class FlexApi extends Domain
{
    protected $_v1;

    /**
     * Construct the FlexApi Domain.
     *
     * @param Client $client Client to communicate with Twilio
     */
    public function __construct(Client $client)
    {
        parent::__construct($client);

        $this->baseUrl = 'https://flex-api.twilio.com';
    }

    /**
     * Magic getter to lazy load version.
     *
     * @param string $name Version to return
     *
     * @throws TwilioException For unknown versions
     *
     * @return \Twilio\Version The requested version
     */
    public function __get(string $name)
    {
        $method = 'get'.\ucfirst($name);
        if (\method_exists($this, $method)) {
            return $this->{$method}();
        }

        throw new TwilioException('Unknown version '.$name);
    }

    /**
     * Magic caller to get resource contexts.
     *
     * @param string $name      Resource to return
     * @param array  $arguments Context parameters
     *
     * @throws TwilioException For unknown resource
     *
     * @return \Twilio\InstanceContext The requested resource context
     */
    public function __call(string $name, array $arguments)
    {
        $method = 'context'.\ucfirst($name);
        if (\method_exists($this, $method)) {
            return \call_user_func_array([$this, $method], $arguments);
        }

        throw new TwilioException('Unknown context '.$name);
    }

    /**
     * Provide a friendly representation.
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string
    {
        return '[Twilio.FlexApi]';
    }

    /**
     * @return V1 Version v1 of flex_api
     */
    protected function getV1(): V1
    {
        if (!$this->_v1) {
            $this->_v1 = new V1($this);
        }

        return $this->_v1;
    }

    protected function getChannel(): FlexApi\V1\ChannelList
    {
        return $this->v1->channel;
    }

    /**
     * @param string $sid The SID that identifies the Flex chat channel resource to
     *                    fetch
     */
    protected function contextChannel(string $sid): FlexApi\V1\ChannelContext
    {
        return $this->v1->channel($sid);
    }

    protected function getConfiguration(): FlexApi\V1\ConfigurationList
    {
        return $this->v1->configuration;
    }

    protected function contextConfiguration(): FlexApi\V1\ConfigurationContext
    {
        return $this->v1->configuration();
    }

    protected function getFlexFlow(): FlexApi\V1\FlexFlowList
    {
        return $this->v1->flexFlow;
    }

    /**
     * @param string $sid The SID that identifies the resource to fetch
     */
    protected function contextFlexFlow(string $sid): FlexApi\V1\FlexFlowContext
    {
        return $this->v1->flexFlow($sid);
    }

    protected function getWebChannel(): FlexApi\V1\WebChannelList
    {
        return $this->v1->webChannel;
    }

    /**
     * @param string $sid The SID of the WebChannel resource to fetch
     */
    protected function contextWebChannel(string $sid): FlexApi\V1\WebChannelContext
    {
        return $this->v1->webChannel($sid);
    }
}
