<?php

declare(strict_types=1);

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0.
 * /       /
 */

namespace Twilio\Rest;

use Twilio\Domain;
use Twilio\Exceptions\TwilioException;
use Twilio\Rest\Messaging\V1;

/**
 * @property \Twilio\Rest\Messaging\V1                       $v1
 * @property \Twilio\Rest\Messaging\V1\BrandRegistrationList $brandRegistrations
 * @property \Twilio\Rest\Messaging\V1\DeactivationsList     $deactivations
 * @property \Twilio\Rest\Messaging\V1\ExternalCampaignList  $externalCampaign
 * @property \Twilio\Rest\Messaging\V1\ServiceList           $services
 * @property \Twilio\Rest\Messaging\V1\UsecaseList           $usecases
 *
 * @method \Twilio\Rest\Messaging\V1\BrandRegistrationContext brandRegistrations(string $sid)
 * @method \Twilio\Rest\Messaging\V1\DeactivationsContext     deactivations()
 * @method \Twilio\Rest\Messaging\V1\ServiceContext           services(string $sid)
 */
class Messaging extends Domain
{
    protected $_v1;

    /**
     * Construct the Messaging Domain.
     *
     * @param Client $client Client to communicate with Twilio
     */
    public function __construct(Client $client)
    {
        parent::__construct($client);

        $this->baseUrl = 'https://messaging.twilio.com';
    }

    /**
     * Magic getter to lazy load version.
     *
     * @param string $name Version to return
     *
     * @throws TwilioException For unknown versions
     *
     * @return \Twilio\Version The requested version
     */
    public function __get(string $name)
    {
        $method = 'get'.\ucfirst($name);
        if (\method_exists($this, $method)) {
            return $this->{$method}();
        }

        throw new TwilioException('Unknown version '.$name);
    }

    /**
     * Magic caller to get resource contexts.
     *
     * @param string $name      Resource to return
     * @param array  $arguments Context parameters
     *
     * @throws TwilioException For unknown resource
     *
     * @return \Twilio\InstanceContext The requested resource context
     */
    public function __call(string $name, array $arguments)
    {
        $method = 'context'.\ucfirst($name);
        if (\method_exists($this, $method)) {
            return \call_user_func_array([$this, $method], $arguments);
        }

        throw new TwilioException('Unknown context '.$name);
    }

    /**
     * Provide a friendly representation.
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string
    {
        return '[Twilio.Messaging]';
    }

    /**
     * @return V1 Version v1 of messaging
     */
    protected function getV1(): V1
    {
        if (!$this->_v1) {
            $this->_v1 = new V1($this);
        }

        return $this->_v1;
    }

    protected function getBrandRegistrations(): Messaging\V1\BrandRegistrationList
    {
        return $this->v1->brandRegistrations;
    }

    /**
     * @param string $sid The SID that identifies the resource to fetch
     */
    protected function contextBrandRegistrations(string $sid): Messaging\V1\BrandRegistrationContext
    {
        return $this->v1->brandRegistrations($sid);
    }

    protected function getDeactivations(): Messaging\V1\DeactivationsList
    {
        return $this->v1->deactivations;
    }

    protected function contextDeactivations(): Messaging\V1\DeactivationsContext
    {
        return $this->v1->deactivations();
    }

    protected function getExternalCampaign(): Messaging\V1\ExternalCampaignList
    {
        return $this->v1->externalCampaign;
    }

    protected function getServices(): Messaging\V1\ServiceList
    {
        return $this->v1->services;
    }

    /**
     * @param string $sid The SID that identifies the resource to fetch
     */
    protected function contextServices(string $sid): Messaging\V1\ServiceContext
    {
        return $this->v1->services($sid);
    }

    protected function getUsecases(): Messaging\V1\UsecaseList
    {
        return $this->v1->usecases;
    }
}
