<?php

declare(strict_types=1);

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0.
 * /       /
 */

namespace Twilio\Rest;

use Twilio\Domain;
use Twilio\Exceptions\TwilioException;
use Twilio\Rest\Supersim\V1;

/**
 * @property \Twilio\Rest\Supersim\V1                          $v1
 * @property \Twilio\Rest\Supersim\V1\CommandList              $commands
 * @property \Twilio\Rest\Supersim\V1\FleetList                $fleets
 * @property \Twilio\Rest\Supersim\V1\NetworkList              $networks
 * @property \Twilio\Rest\Supersim\V1\NetworkAccessProfileList $networkAccessProfiles
 * @property \Twilio\Rest\Supersim\V1\SimList                  $sims
 * @property \Twilio\Rest\Supersim\V1\SmsCommandList           $smsCommands
 * @property \Twilio\Rest\Supersim\V1\UsageRecordList          $usageRecords
 *
 * @method \Twilio\Rest\Supersim\V1\CommandContext              commands(string $sid)
 * @method \Twilio\Rest\Supersim\V1\FleetContext                fleets(string $sid)
 * @method \Twilio\Rest\Supersim\V1\NetworkContext              networks(string $sid)
 * @method \Twilio\Rest\Supersim\V1\NetworkAccessProfileContext networkAccessProfiles(string $sid)
 * @method \Twilio\Rest\Supersim\V1\SimContext                  sims(string $sid)
 * @method \Twilio\Rest\Supersim\V1\SmsCommandContext           smsCommands(string $sid)
 */
class Supersim extends Domain
{
    protected $_v1;

    /**
     * Construct the Supersim Domain.
     *
     * @param Client $client Client to communicate with Twilio
     */
    public function __construct(Client $client)
    {
        parent::__construct($client);

        $this->baseUrl = 'https://supersim.twilio.com';
    }

    /**
     * Magic getter to lazy load version.
     *
     * @param string $name Version to return
     *
     * @throws TwilioException For unknown versions
     *
     * @return \Twilio\Version The requested version
     */
    public function __get(string $name)
    {
        $method = 'get'.\ucfirst($name);
        if (\method_exists($this, $method)) {
            return $this->{$method}();
        }

        throw new TwilioException('Unknown version '.$name);
    }

    /**
     * Magic caller to get resource contexts.
     *
     * @param string $name      Resource to return
     * @param array  $arguments Context parameters
     *
     * @throws TwilioException For unknown resource
     *
     * @return \Twilio\InstanceContext The requested resource context
     */
    public function __call(string $name, array $arguments)
    {
        $method = 'context'.\ucfirst($name);
        if (\method_exists($this, $method)) {
            return \call_user_func_array([$this, $method], $arguments);
        }

        throw new TwilioException('Unknown context '.$name);
    }

    /**
     * Provide a friendly representation.
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string
    {
        return '[Twilio.Supersim]';
    }

    /**
     * @return V1 Version v1 of supersim
     */
    protected function getV1(): V1
    {
        if (!$this->_v1) {
            $this->_v1 = new V1($this);
        }

        return $this->_v1;
    }

    protected function getCommands(): Supersim\V1\CommandList
    {
        return $this->v1->commands;
    }

    /**
     * @param string $sid The SID that identifies the resource to fetch
     */
    protected function contextCommands(string $sid): Supersim\V1\CommandContext
    {
        return $this->v1->commands($sid);
    }

    protected function getFleets(): Supersim\V1\FleetList
    {
        return $this->v1->fleets;
    }

    /**
     * @param string $sid The SID that identifies the resource to fetch
     */
    protected function contextFleets(string $sid): Supersim\V1\FleetContext
    {
        return $this->v1->fleets($sid);
    }

    protected function getNetworks(): Supersim\V1\NetworkList
    {
        return $this->v1->networks;
    }

    /**
     * @param string $sid The SID of the Network resource to fetch
     */
    protected function contextNetworks(string $sid): Supersim\V1\NetworkContext
    {
        return $this->v1->networks($sid);
    }

    protected function getNetworkAccessProfiles(): Supersim\V1\NetworkAccessProfileList
    {
        return $this->v1->networkAccessProfiles;
    }

    /**
     * @param string $sid The SID that identifies the resource to fetch
     */
    protected function contextNetworkAccessProfiles(string $sid): Supersim\V1\NetworkAccessProfileContext
    {
        return $this->v1->networkAccessProfiles($sid);
    }

    protected function getSims(): Supersim\V1\SimList
    {
        return $this->v1->sims;
    }

    /**
     * @param string $sid The SID that identifies the resource to fetch
     */
    protected function contextSims(string $sid): Supersim\V1\SimContext
    {
        return $this->v1->sims($sid);
    }

    protected function getSmsCommands(): Supersim\V1\SmsCommandList
    {
        return $this->v1->smsCommands;
    }

    /**
     * @param string $sid The SID that identifies the resource to fetch
     */
    protected function contextSmsCommands(string $sid): Supersim\V1\SmsCommandContext
    {
        return $this->v1->smsCommands($sid);
    }

    protected function getUsageRecords(): Supersim\V1\UsageRecordList
    {
        return $this->v1->usageRecords;
    }
}
