<?php

declare(strict_types=1);

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0.
 * /       /
 */

namespace Twilio\Rest\Accounts\V1;

use Twilio\Exceptions\TwilioException;
use Twilio\InstanceContext;
use Twilio\Version;

class AuthTokenPromotionContext extends InstanceContext
{
    /**
     * Initialize the AuthTokenPromotionContext.
     *
     * @param Version $version Version that contains the resource
     */
    public function __construct(Version $version)
    {
        parent::__construct($version);

        // Path Solution
        $this->solution = [];

        $this->uri = '/AuthTokens/Promote';
    }

    /**
     * Provide a friendly representation.
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string
    {
        $context = [];
        foreach ($this->solution as $key => $value) {
            $context[] = "{$key}={$value}";
        }

        return '[Twilio.Accounts.V1.AuthTokenPromotionContext '.\implode(' ', $context).']';
    }

    /**
     * Update the AuthTokenPromotionInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return AuthTokenPromotionInstance Updated AuthTokenPromotionInstance
     */
    public function update(): AuthTokenPromotionInstance
    {
        $payload = $this->version->update('POST', $this->uri);

        return new AuthTokenPromotionInstance($this->version, $payload);
    }
}
