<?php

declare(strict_types=1);

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0.
 * /       /
 */

namespace Twilio\Rest\Accounts\V1;

use Twilio\Deserialize;
use Twilio\Exceptions\TwilioException;
use Twilio\InstanceResource;
use Twilio\Values;
use Twilio\Version;

/**
 * @property string    $accountSid
 * @property \DateTime $dateCreated
 * @property \DateTime $dateUpdated
 * @property string    $secondaryAuthToken
 * @property string    $url
 */
class SecondaryAuthTokenInstance extends InstanceResource
{
    /**
     * Initialize the SecondaryAuthTokenInstance.
     *
     * @param Version $version Version that contains the resource
     * @param mixed[] $payload The response payload
     */
    public function __construct(Version $version, array $payload)
    {
        parent::__construct($version);

        // Marshaled Properties
        $this->properties = [
            'accountSid' => Values::array_get($payload, 'account_sid'),
            'dateCreated' => Deserialize::dateTime(Values::array_get($payload, 'date_created')),
            'dateUpdated' => Deserialize::dateTime(Values::array_get($payload, 'date_updated')),
            'secondaryAuthToken' => Values::array_get($payload, 'secondary_auth_token'),
            'url' => Values::array_get($payload, 'url'),
        ];

        $this->solution = [];
    }

    /**
     * Magic getter to access properties.
     *
     * @param string $name Property to access
     *
     * @throws TwilioException For unknown properties
     *
     * @return mixed The requested property
     */
    public function __get(string $name)
    {
        if (\array_key_exists($name, $this->properties)) {
            return $this->properties[$name];
        }

        if (\property_exists($this, '_'.$name)) {
            $method = 'get'.\ucfirst($name);

            return $this->{$method}();
        }

        throw new TwilioException('Unknown property: '.$name);
    }

    /**
     * Provide a friendly representation.
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string
    {
        $context = [];
        foreach ($this->solution as $key => $value) {
            $context[] = "{$key}={$value}";
        }

        return '[Twilio.Accounts.V1.SecondaryAuthTokenInstance '.\implode(' ', $context).']';
    }

    /**
     * Create the SecondaryAuthTokenInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return SecondaryAuthTokenInstance Created SecondaryAuthTokenInstance
     */
    public function create(): SecondaryAuthTokenInstance
    {
        return $this->proxy()->create();
    }

    /**
     * Delete the SecondaryAuthTokenInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return bool True if delete succeeds, false otherwise
     */
    public function delete(): bool
    {
        return $this->proxy()->delete();
    }

    /**
     * Generate an instance context for the instance, the context is capable of
     * performing various actions.  All instance actions are proxied to the context.
     *
     * @return SecondaryAuthTokenContext Context for this SecondaryAuthTokenInstance
     */
    protected function proxy(): SecondaryAuthTokenContext
    {
        if (!$this->context) {
            $this->context = new SecondaryAuthTokenContext($this->version);
        }

        return $this->context;
    }
}
