<?php

declare(strict_types=1);

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0.
 * /       /
 */

namespace Twilio\Rest\Conversations\V1\Conversation;

use Twilio\Exceptions\TwilioException;
use Twilio\InstanceContext;
use Twilio\Options;
use Twilio\Serialize;
use Twilio\Values;
use Twilio\Version;

class WebhookContext extends InstanceContext
{
    /**
     * Initialize the WebhookContext.
     *
     * @param Version $version         Version that contains the resource
     * @param string  $conversationSid the unique ID of the Conversation for this
     *                                 webhook
     * @param string  $sid             a 34 character string that uniquely identifies this
     *                                 resource
     */
    public function __construct(Version $version, $conversationSid, $sid)
    {
        parent::__construct($version);

        // Path Solution
        $this->solution = ['conversationSid' => $conversationSid, 'sid' => $sid];

        $this->uri = '/Conversations/'.\rawurlencode($conversationSid).'/Webhooks/'.\rawurlencode($sid).'';
    }

    /**
     * Provide a friendly representation.
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string
    {
        $context = [];
        foreach ($this->solution as $key => $value) {
            $context[] = "{$key}={$value}";
        }

        return '[Twilio.Conversations.V1.WebhookContext '.\implode(' ', $context).']';
    }

    /**
     * Fetch the WebhookInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return WebhookInstance Fetched WebhookInstance
     */
    public function fetch(): WebhookInstance
    {
        $payload = $this->version->fetch('GET', $this->uri);

        return new WebhookInstance(
            $this->version,
            $payload,
            $this->solution['conversationSid'],
            $this->solution['sid']
        );
    }

    /**
     * Update the WebhookInstance.
     *
     * @param array|Options $options Optional Arguments
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return WebhookInstance Updated WebhookInstance
     */
    public function update(array $options = []): WebhookInstance
    {
        $options = new Values($options);

        $data = Values::of([
            'Configuration.Url' => $options['configurationUrl'],
            'Configuration.Method' => $options['configurationMethod'],
            'Configuration.Filters' => Serialize::map($options['configurationFilters'], fn ($e) => $e),
            'Configuration.Triggers' => Serialize::map($options['configurationTriggers'], fn ($e) => $e),
            'Configuration.FlowSid' => $options['configurationFlowSid'],
        ]);

        $payload = $this->version->update('POST', $this->uri, [], $data);

        return new WebhookInstance(
            $this->version,
            $payload,
            $this->solution['conversationSid'],
            $this->solution['sid']
        );
    }

    /**
     * Delete the WebhookInstance.
     *
     * @throws TwilioException when an HTTP error occurs
     *
     * @return bool True if delete succeeds, false otherwise
     */
    public function delete(): bool
    {
        return $this->version->delete('DELETE', $this->uri);
    }
}
