<?php

declare(strict_types=1);

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0.
 * /       /
 */

namespace Twilio\TwiML\Voice;

use Twilio\TwiML\TwiML;

class Say extends TwiML
{
    /**
     * Say constructor.
     *
     * @param string $message    Message to say
     * @param array  $attributes Optional attributes
     */
    public function __construct($message, $attributes = [])
    {
        parent::__construct('Say', $message, $attributes);
    }

    /**
     * Add Break child.
     *
     * @param array $attributes Optional attributes
     *
     * @return SsmlBreak child element
     */
    public function break_($attributes = []): SsmlBreak
    {
        return $this->nest(new SsmlBreak($attributes));
    }

    /**
     * Add Emphasis child.
     *
     * @param string $words      Words to emphasize
     * @param array  $attributes Optional attributes
     *
     * @return SsmlEmphasis child element
     */
    public function emphasis($words, $attributes = []): SsmlEmphasis
    {
        return $this->nest(new SsmlEmphasis($words, $attributes));
    }

    /**
     * Add Lang child.
     *
     * @param string $words      Words to speak
     * @param array  $attributes Optional attributes
     *
     * @return SsmlLang child element
     */
    public function lang($words, $attributes = []): SsmlLang
    {
        return $this->nest(new SsmlLang($words, $attributes));
    }

    /**
     * Add P child.
     *
     * @param string $words Words to speak
     *
     * @return SsmlP child element
     */
    public function p($words): SsmlP
    {
        return $this->nest(new SsmlP($words));
    }

    /**
     * Add Phoneme child.
     *
     * @param string $words      Words to speak
     * @param array  $attributes Optional attributes
     *
     * @return SsmlPhoneme child element
     */
    public function phoneme($words, $attributes = []): SsmlPhoneme
    {
        return $this->nest(new SsmlPhoneme($words, $attributes));
    }

    /**
     * Add Prosody child.
     *
     * @param string $words      Words to speak
     * @param array  $attributes Optional attributes
     *
     * @return SsmlProsody child element
     */
    public function prosody($words, $attributes = []): SsmlProsody
    {
        return $this->nest(new SsmlProsody($words, $attributes));
    }

    /**
     * Add S child.
     *
     * @param string $words Words to speak
     *
     * @return SsmlS child element
     */
    public function s($words): SsmlS
    {
        return $this->nest(new SsmlS($words));
    }

    /**
     * Add Say-As child.
     *
     * @param string $words      Words to be interpreted
     * @param array  $attributes Optional attributes
     *
     * @return SsmlSayAs child element
     */
    public function say_As($words, $attributes = []): SsmlSayAs
    {
        return $this->nest(new SsmlSayAs($words, $attributes));
    }

    /**
     * Add Sub child.
     *
     * @param string $words      Words to be substituted
     * @param array  $attributes Optional attributes
     *
     * @return SsmlSub child element
     */
    public function sub($words, $attributes = []): SsmlSub
    {
        return $this->nest(new SsmlSub($words, $attributes));
    }

    /**
     * Add W child.
     *
     * @param string $words      Words to speak
     * @param array  $attributes Optional attributes
     *
     * @return SsmlW child element
     */
    public function w($words, $attributes = []): SsmlW
    {
        return $this->nest(new SsmlW($words, $attributes));
    }

    /**
     * Add Voice attribute.
     *
     * @param string $voice Voice to use
     */
    public function setVoice($voice): self
    {
        return $this->setAttribute('voice', $voice);
    }

    /**
     * Add Loop attribute.
     *
     * @param int $loop Times to loop message
     */
    public function setLoop($loop): self
    {
        return $this->setAttribute('loop', $loop);
    }

    /**
     * Add Language attribute.
     *
     * @param string $language Message langauge
     */
    public function setLanguage($language): self
    {
        return $this->setAttribute('language', $language);
    }
}
